
import shap
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

FEATURE_DISPLAY = {
    "age":              "Age",
    "stage":            "Cancer Stage",
    "bmi":              "BMI",
    "prior_surgeries":  "Prior Surgeries",
    "comorbidities":    "Comorbidities",
    "performance_status":"Performance Status",
    "smoking":          "Smoking History",
    "diabetes":         "Diabetes",
    "family_history":   "Family History",
    "metastasis":       "Metastasis",
    "cancer_type":      "Cancer Type",
    "treatment_type":   "Treatment Type",
}

class SHAPExplainer:
    def __init__(self, model, X_train):
        self.explainer   = shap.TreeExplainer(model)
        self.X_train     = X_train

    def explain(self, X_encoded):
        return self.explainer.shap_values(X_encoded)

    def plot_shap(self, shap_values, X_encoded, predicted_tier: int) -> str:
        """Generate a clean SHAP bar chart, return file path."""
        sv   = shap_values[predicted_tier][0]   # values for predicted class
        cols = X_encoded.columns.tolist()

        # Sort by absolute value
        order  = np.argsort(np.abs(sv))[::-1]
        names  = [FEATURE_DISPLAY.get(cols[i], cols[i]) for i in order]
        values = sv[order]

        colors = ["#ef4444" if v > 0 else "#22c55e" for v in values]

        fig, ax = plt.subplots(figsize=(8, 5))
        fig.patch.set_facecolor("#0f172a")
        ax.set_facecolor("#0f172a")

        bars = ax.barh(names[::-1], values[::-1], color=colors[::-1], height=0.6)

        ax.set_xlabel("SHAP Value (impact on risk score)", color="white", fontsize=10)
        ax.set_title("Feature Impact on Risk Prediction", color="white",
                     fontsize=13, fontweight="bold", pad=12)
        ax.tick_params(colors="white")
        ax.spines[["top","right","left","bottom"]].set_visible(False)
        ax.axvline(0, color="#475569", linewidth=0.8)

        red_patch   = mpatches.Patch(color="#ef4444", label="Increases Risk")
        green_patch = mpatches.Patch(color="#22c55e", label="Decreases Risk")
        ax.legend(handles=[red_patch, green_patch], facecolor="#1e293b",
                  labelcolor="white", fontsize=9, loc="lower right")

        plt.tight_layout()
        path = "/content/shap_chart.png"
        plt.savefig(path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
        plt.close()
        return path

    def top_factors(self, shap_values, X_encoded, tier: int, n=5):
        sv    = shap_values[tier][0]
        cols  = X_encoded.columns.tolist()
        order = np.argsort(np.abs(sv))[::-1][:n]
        return [
            {
                "feature": FEATURE_DISPLAY.get(cols[i], cols[i]),
                "direction": "increases" if sv[i] > 0 else "decreases",
                "magnitude": abs(sv[i]),
            }
            for i in order
        ]

    def explanation_text(self, factors, tier_label: str) -> str:
        lines = [f"The model classified this patient as **{tier_label}** based on:"]
        for f in factors:
            arrow = "↑" if f["direction"] == "increases" else "↓"
            lines.append(f"  {arrow} **{f['feature']}** — {f['direction']} risk")
        lines.append("\n_This analysis is generated by an Explainable AI model "
                     "for informational purposes only. Always consult a physician._")
        return "\n\n".join(lines)
